trigger:
  - master

pr:
  - master
  - dev

pool:
  vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python36: 
        python.version: '3.6'
      Python37:
        python.version: '3.7'

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
    displayName: "Update pip"

  - script: |
      python -m pip install -r requirements.txt
    displayName: "Install requirements"

  - script: |
      python -m pip install pylint
      pylint boston/*.py
      pylint iris/*.py
    displayName: "Linting"

  - script: |
      pip install pytest pytest-azurepipelines
      python -m pytest tests/
    displayName: 'Test with pytest'